name: Build and Publish NuGet Package

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean
        run: dotnet clean
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -C Release

      - name: Pack
        run: dotnet pack .\src\OpenMediator\OpenMediator.csproj -c Release -o ./nupkgs --no-build 

      - name: Push to NuGet.org
        run: dotnet nuget push ./nupkgs/*.nupkg --source ${{ secrets.NUGET_URL }} --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
            name: files
            path: nupkgs